name: CI

on: [push, pull_request]

jobs:


  build:
    runs-on: ubuntu-20.04
    container:
      image: alpine:3.16
    strategy:
      matrix:
        model: ["TS80P"]
      fail-fast: true

    steps:
      - name: Install dependencies (apk)
        run: apk add --no-cache gcc-riscv-none-elf gcc-arm-none-eabi newlib-riscv-none-elf newlib-arm-none-eabi findutils python3 py3-pip make git bash

      - name: Install dependencies (python)
        run: python3 -m pip install bdflib

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Git ownership exception
        run: git config --global --add safe.directory /__w/IronOS/IronOS && git config --global safe.directory "$GITHUB_WORKSPACE"

      - name: Git meta info
        run: echo "GITHUB_CI_PR_SHA=${{github.event.pull_request.head.sha}}" >> "${GITHUB_ENV}"

      - name: Build ${{ matrix.model }}
        run: cd source && ./build.sh -m ${{ matrix.model }}

      - name: Copy license files
        run: cp LICENSE scripts/LICENSE_RELEASE.md  source/Hexfile/

      - name: Archive ${{ matrix.model }} artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.model }}
          path: |
            source/Hexfile/${{ matrix.model }}_*.hex
            source/Hexfile/${{ matrix.model }}_*.dfu
            source/Hexfile/${{ matrix.model }}_*.bin
            source/Hexfile/LICENSE
            source/Hexfile/LICENSE_RELEASE.md
          if-no-files-found: error

      - name: Generate json index file
        run: ./source/metadata.py ${{ matrix.model }}.json

      - name: Archive ${{ matrix.model }} index file
        uses: actions/upload-artifact@v3
        with:
          name: metadata
          path: source/Hexfile/${{ matrix.model }}.json